[funfacts]
title = "The Yeshiva World"
url = "https://www.theyeshivaworld.com/news/category/headlines-breaking-stories"
entrySelector = ".item-details"
titleSelector = "h3"
linkSelector = "a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
